language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t surbitonix97/docker-react-webapp -f Dockerfile.dev .

script:
  - docker run -e CI=true surbitonix97/docker-react-webapp npm run test